version: '3.7'

services:

  sample:
    container_name: test-task
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/test-task'
      - '/test-task/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true