FROM node:16.8.0-buster as build

WORKDIR /test-task

ENV PATH /test-task/node_modules/.bin:$PATH

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --silent

COPY . .

RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=build /test-task/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]